export const UI_ASSET_KEYS = Object.freeze({
    BLANK: 'UI_ASSET_KEYS.BLANK',
    FONT: 'DUNGEON_ASSET_KEYS.FONT',
    SKILL: 'UI_ASSET_KEYS.SKILL',
    BUBBLE: 'UI_ASSET_KEYS.BUBBLE',
});

export const DUNGEON_ASSET_KEYS = Object.freeze({
    CARD: 'DUNGEON_ASSET_KEYS.CARD',
    UNIT: 'DUNGEON_ASSET_KEYS.UNIT',
    WORLD: 'DUNGEON_ASSET_KEYS.WORLD',
    EFFECT: 'DUNGEON_ASSET_KEYS.EFFECT',
    FONT: 'DUNGEON_ASSET_KEYS.FONT',
});

export const MAP_ASSET_KEYS = Object.freeze({
    WORLD: 'MAP_ASSET_KEYS.WORLD',
    UNIT: 'MAP_ASSET_KEYS.UNIT',
    SELECTION: 'MAP_ASSET_KEYS.SELECTION',
});

export const DATA_ASSET_KEYS = Object.freeze({
    UNIT: 'DATA_ASSET_KEYS.UNIT',
    ITEM: 'DATA_ASSET_KEYS.ITEM',
});
