export const DATA_ASSET_KEYS = Object.freeze({
    DUNGEON_THEMES: 'DUNGEON_THEMES',
    LEVELS: 'LEVELS',
});

export const DUNGEON_ASSET_KEYS = Object.freeze({
    DUNGEON: 'DUNGEON',
});

export const UI_ASSET_KEYS = Object.freeze({
    TRANSPARENT: 'TRANSPARENT',
    DUNGEON_SELECTOR: 'DUNGEON_SELECTOR',
    LEVEL_SELECTOR: 'LEVEL_SELECTOR',
    BUTTON: 'BUTTON',
    TEXT_BUTTON: 'TEXT_BUTTON',
    ICONS: 'ICONS',
    SMALL_FONT: 'SMALL_FONT',   // 10, 20, 30
    LARGE_FONT: 'LARGE_FONT',   // 12, 24, 36
});

