export const SCENE_KEYS = Object.freeze({
    PRELOAD_SCENE: 'PRELOAD_SCENE',
    TITLE_SCENE: 'TITLE_SCENE',
    CREDITS_SCENE: 'CREDITS_SCENE',
    LEVEL_SCENE: 'LEVEL_SCENE',
    DUNGEON_SCENE: 'DUNGEON_SCENE',
});
